version: '3'

services:
  # Database
  db:
    build: ./mariadb/
    container_name: mariadbwp
    entrypoint: sh home/root/init.sh
    command: tail -F anything
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - wpsite
  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    build: ./phpmyadmin/
    entrypoint: sh ../start.sh
    command: tail -F anything
    restart: always
    ports:
      - '1234:80'
      - '1235:443'
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    build: ./wordpress/
    entrypoint: sh ../start.sh
    command: tail -F anything
    ports:
      - '1111:80'
      - '1112:443'
    restart: always
    volumes: ['./:/var/www/html']
    networks:
      - wpsite
networks:
  wpsite:
volumes:
    mysql-dump: